name: cmdlinesatellitecopymovedetector
    - conda-forge
    - anaconda
    - defaults
dependencies:
    - gdal
    - pocl
    - pip
    - python==3.7.6
    - tensorflow-cpu==1.15.0
    - pip:
        - numpy==1.19.4
        - rawpy==0.15.0
        - opencv-python==4.5.2
        - matplotlib==3.3.3
        - scikit-image==0=0.17.2
        - scipy==1.5.4
        - scikit-learn==0.23.2
        - silx==0.13.2    
        - tqdm==4.54.1
        - pyopencl==2020.3.1
        - Pillow==8.0.1
        - glymur==0.8.1
